name: Deploy to s3 static website

on:
  pull_request:
    branches:
      - static-serve 
  push:
    branches:
      - static-serve 
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch names in lowercase
        id: extract
        shell: bash
        run: |
          echo "$(echo ${GITHUB_HEAD_REF,,})"
          echo "$(echo ${GITHUB_BASE_REF,,})"
          echo "##[set-output name=head_bn;]$(echo ${GITHUB_HEAD_REF,,})"
          echo "##[set-output name=base_bn;]$(echo ${GITHUB_HEAD_REF,,})"
      - name: Create bucket name(s)
        id: mb
        shell: bash
        run: |
          echo "##[set-output name=new_bucket_name;]${{ format( 's3://{0}-{1}', secrets.BUCKET_NAME, steps.extract.outputs.head_bn ) }}"
          if [ ${{ github.event.pull_request.merged }} -eq 'true' ]; then
            echo "##[set-output name=old_bucket_name;]${{ format( 's3://{0}-{1}', secrets.BUCKET_NAME, steps.extract.outputs.base_bn ) }}"
          fi
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: |
#           echo "This step is not commented out."
#           # echo "$GITHUB_CONTEXT"
#           echo ${{ github.head_ref }}
#           echo ${{ github.base_ref }}
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: AWS Identity
        run:  aws sts get-caller-identity
      - name: Enable static website
        run: |
          BUCKET_EXISTS=$(aws s3api head-bucket --bucket ${{ steps.mb.outputs.new_bucket_name }} 2>&1 || true)
          if [ -z "$BUCKET_EXISTS" ]; then
            echo "Bucket exists"
            if [ ${{ github.event.pull_request.merged }} -eq 'true' ]; then
              aws s3 rb ${{ format( 's3://{0}', steps.mb.outputs.old_bucket_name ) }} --force
            fi
          else
            echo "Bucket does not exist"
            echo "${{ format( 's3://{0}', steps.mb.outputs.new_bucket_name ) }}"
            echo "${{ format( 's3://{0}', steps.mb.outputs.new_bucket_name ) }}"
            # aws s3 mb ${{ format( 's3://{0}', steps.mb.outputs.new_bucket_name ) }}
            # aws s3 website ${{ format('s3://{0}/', steps.mb.outputs.new_bucket_name ) }} --index-document index.html --error-document error.html
            # # Need to have "s3_read_policy.json" file in repo under .github folder.
            # cd .github
            # sed -i "${{ format('s/BUCKET_NAME/{0}/g', steps.mb.outputs.new_bucket_name ) }}" s3_read_policy.json
            # # Need to have this file in repo
            # aws s3api put-bucket-policy --bucket ${{ format('{0}', steps.mb.outputs.new_bucket_name ) }} --policy file://.github/s3_read_policy.json
            # cd ..
          fi
